#pragma once

#include "NativeGameplayTags.h"

#pragma region grid
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Grid_Chunk_Size)

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Grid_Cell_Size)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Grid_Cell_InvSize)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Grid_Cell_Small_Factor)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Grid_Cell_Big_Factor)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Grid_Cell_Color)

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Grid_Border_Thickness)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Grid_Border_Color)

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Grid_Transition_Length_Factor)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Grid_Transition_Small_CellCountThreshold)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Grid_Transition_Big_CellCountThreshold)
#pragma endregion

#pragma region resource
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Resource_Organic_Wood)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Resource_Organic_Biomass)

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Resource_Mineral_Stone)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Resource_Mineral_Coal)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Resource_Mineral_Iron)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Resource_Mineral_Copper)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Resource_Mineral_Gold)
#pragma endregion